<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Belarus Standard Time">
<General productName="Vugen" productVer="12" os="" host="LXIBY793"><DocLocation><![CDATA[D:\dev\Vuser_Scripts\1.4.2]]></DocLocation></General>
<Doc rID="T1"   productName= "Vugen"  >
<DName><![CDATA[1.4.2]]></DName>
<Res><![CDATA[result1]]></Res>
<Action rID="T2">
<AName><![CDATA[Init]]></AName>
<Summary sTime="11/20/2019 - 18:45:18" eTime="11/20/2019 - 18:45:18" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="5" >
<Disp><![CDATA[Init Summary]]></Disp>
</NodeArgs>
</Action>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Navigate to https://procurepartestc1.../site#Shell-home was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:45:22]]></Time>
<TimeTick>1574264722</TimeTick>
<NodeArgs eType="General" icon="0" nRep="9" status="Passed" >
<Disp><![CDATA[Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.1: Type yauhen.hedrevich@sap.com in Welcome to Procurement... textbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:45:31]]></Time>
<TimeTick>1574264731</TimeTick>
<NodeArgs eType="General" icon="0" nRep="10" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.4: Type ************** in Password passwordbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:45:35]]></Time>
<TimeTick>1574264735</TimeTick>
<NodeArgs eType="General" icon="0" nRep="11" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2.5: Click on Log On button was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:45:44]]></Time>
<TimeTick>1574264744</TimeTick>
<NodeArgs eType="General" icon="0" nRep="12" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[4: Click on link (1) link was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:45:45]]></Time>
<TimeTick>1574264745</TimeTick>
<NodeArgs eType="General" icon="0" nRep="13" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[5: Click on Invoice Document No. textbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:45:53]]></Time>
<TimeTick>1574264753</TimeTick>
<NodeArgs eType="General" icon="0" nRep="14" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[6: Type 5105600147 in Invoice Document No. textbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:45:57]]></Time>
<TimeTick>1574264757</TimeTick>
<NodeArgs eType="General" icon="0" nRep="15" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[8: Click on Invoicing Party / AN...  was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:45:58]]></Time>
<TimeTick>1574264758</TimeTick>
<NodeArgs eType="General" icon="0" nRep="16" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[10: Click on Go  was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:45:59]]></Time>
<TimeTick>1574264759</TimeTick>
<NodeArgs eType="General" icon="0" nRep="17" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[12: Click on Invoicing Party / AN... gridcell was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:46:00]]></Time>
<TimeTick>1574264760</TimeTick>
<NodeArgs eType="General" icon="0" nRep="18" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[14: Click on More button was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:46:04]]></Time>
<TimeTick>1574264764</TimeTick>
<NodeArgs eType="General" icon="0" nRep="19" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[16: Click on Attachments option was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:46:05]]></Time>
<TimeTick>1574264765</TimeTick>
<NodeArgs eType="General" icon="0" nRep="20" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until image (1) image exists was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:46:07]]></Time>
<TimeTick>1574264767</TimeTick>
<NodeArgs eType="General" icon="0" nRep="21" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[18: Click on STATUSInvoice.png  was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:46:07]]></Time>
<TimeTick>1574264767</TimeTick>
<NodeArgs eType="General" icon="0" nRep="22" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11/20/2019 - 18:45:18" eTime="11/20/2019 - 18:46:07" passed="14" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="8" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="7" status="Passed" >
<Disp><![CDATA[1.4.2 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T19" iterID="2" >
<Action rID="T20">
<AName><![CDATA[Action]]></AName>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Navigate to https://procurepartestc1.../site#Shell-home was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:46:31]]></Time>
<TimeTick>1574264791</TimeTick>
<NodeArgs eType="General" icon="0" nRep="27" status="Passed" >
<Disp><![CDATA[Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.1: Type yauhen.hedrevich@sap.com in Welcome to Procurement... textbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:46:39]]></Time>
<TimeTick>1574264799</TimeTick>
<NodeArgs eType="General" icon="0" nRep="28" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.4: Type ************** in Password passwordbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:46:45]]></Time>
<TimeTick>1574264805</TimeTick>
<NodeArgs eType="General" icon="0" nRep="29" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2.5: Click on Log On button was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:46:55]]></Time>
<TimeTick>1574264815</TimeTick>
<NodeArgs eType="General" icon="0" nRep="30" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[4: Click on link (1) link was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:46:56]]></Time>
<TimeTick>1574264816</TimeTick>
<NodeArgs eType="General" icon="0" nRep="31" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[5: Click on Invoice Document No. textbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:47:03]]></Time>
<TimeTick>1574264823</TimeTick>
<NodeArgs eType="General" icon="0" nRep="32" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[6: Type 5105600147 in Invoice Document No. textbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:47:06]]></Time>
<TimeTick>1574264826</TimeTick>
<NodeArgs eType="General" icon="0" nRep="33" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[8: Click on Invoicing Party / AN...  was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:47:07]]></Time>
<TimeTick>1574264827</TimeTick>
<NodeArgs eType="General" icon="0" nRep="34" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[10: Click on Go  was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:47:08]]></Time>
<TimeTick>1574264828</TimeTick>
<NodeArgs eType="General" icon="0" nRep="35" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[12: Click on Invoicing Party / AN... gridcell was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:47:12]]></Time>
<TimeTick>1574264832</TimeTick>
<NodeArgs eType="General" icon="0" nRep="36" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[14: Click on More button was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:47:13]]></Time>
<TimeTick>1574264833</TimeTick>
<NodeArgs eType="General" icon="0" nRep="37" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[16: Click on Attachments option was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:47:14]]></Time>
<TimeTick>1574264834</TimeTick>
<NodeArgs eType="General" icon="0" nRep="38" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until image (1) image exists was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:47:16]]></Time>
<TimeTick>1574264836</TimeTick>
<NodeArgs eType="General" icon="0" nRep="39" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[18: Click on STATUSInvoice.png  was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:47:16]]></Time>
<TimeTick>1574264836</TimeTick>
<NodeArgs eType="General" icon="0" nRep="40" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11/20/2019 - 18:46:29" eTime="11/20/2019 - 18:47:16" passed="14" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="26" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="25" status="Passed" >
<Disp><![CDATA[1.4.2 Iteration 2 (Row 2)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T35" iterID="3" >
<Action rID="T36">
<AName><![CDATA[Action]]></AName>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Navigate to https://procurepartestc1.../site#Shell-home was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:47:49]]></Time>
<TimeTick>1574264869</TimeTick>
<NodeArgs eType="General" icon="0" nRep="45" status="Passed" >
<Disp><![CDATA[Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.1: Type yauhen.hedrevich@sap.com in Welcome to Procurement... textbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:47:59]]></Time>
<TimeTick>1574264879</TimeTick>
<NodeArgs eType="General" icon="0" nRep="46" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.4: Type ************** in Password passwordbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:48:06]]></Time>
<TimeTick>1574264886</TimeTick>
<NodeArgs eType="General" icon="0" nRep="47" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2.5: Click on Log On button was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:48:15]]></Time>
<TimeTick>1574264895</TimeTick>
<NodeArgs eType="General" icon="0" nRep="48" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[4: Click on link (1) link was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:48:21]]></Time>
<TimeTick>1574264901</TimeTick>
<NodeArgs eType="General" icon="0" nRep="49" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[5: Click on Invoice Document No. textbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:48:22]]></Time>
<TimeTick>1574264902</TimeTick>
<NodeArgs eType="General" icon="0" nRep="50" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[6: Type 5105600147 in Invoice Document No. textbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:48:27]]></Time>
<TimeTick>1574264907</TimeTick>
<NodeArgs eType="General" icon="0" nRep="51" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[8: Click on Invoicing Party / AN...  was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:48:28]]></Time>
<TimeTick>1574264908</TimeTick>
<NodeArgs eType="General" icon="0" nRep="52" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[10: Click on Go  was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:48:28]]></Time>
<TimeTick>1574264908</TimeTick>
<NodeArgs eType="General" icon="0" nRep="53" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[12: Click on Invoicing Party / AN... gridcell was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:48:33]]></Time>
<TimeTick>1574264913</TimeTick>
<NodeArgs eType="General" icon="0" nRep="54" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[14: Click on More button was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:48:33]]></Time>
<TimeTick>1574264913</TimeTick>
<NodeArgs eType="General" icon="0" nRep="55" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[16: Click on Attachments option was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:48:34]]></Time>
<TimeTick>1574264914</TimeTick>
<NodeArgs eType="General" icon="0" nRep="56" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until image (1) image exists was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:48:36]]></Time>
<TimeTick>1574264916</TimeTick>
<NodeArgs eType="General" icon="0" nRep="57" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[18: Click on STATUSInvoice.png  was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:48:36]]></Time>
<TimeTick>1574264916</TimeTick>
<NodeArgs eType="General" icon="0" nRep="58" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11/20/2019 - 18:47:48" eTime="11/20/2019 - 18:48:36" passed="14" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="44" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="43" status="Passed" >
<Disp><![CDATA[1.4.2 Iteration 3 (Row 3)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T51" iterID="4" >
<Action rID="T52">
<AName><![CDATA[Action]]></AName>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Navigate to https://procurepartestc1.../site#Shell-home was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:49:02]]></Time>
<TimeTick>1574264942</TimeTick>
<NodeArgs eType="General" icon="0" nRep="63" status="Passed" >
<Disp><![CDATA[Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.1: Type yauhen.hedrevich@sap.com in Welcome to Procurement... textbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:49:11]]></Time>
<TimeTick>1574264951</TimeTick>
<NodeArgs eType="General" icon="0" nRep="64" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.4: Type ************** in Password passwordbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:49:17]]></Time>
<TimeTick>1574264957</TimeTick>
<NodeArgs eType="General" icon="0" nRep="65" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2.5: Click on Log On button was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:49:26]]></Time>
<TimeTick>1574264966</TimeTick>
<NodeArgs eType="General" icon="0" nRep="66" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[4: Click on link (1) link was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:49:31]]></Time>
<TimeTick>1574264971</TimeTick>
<NodeArgs eType="General" icon="0" nRep="67" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[5: Click on Invoice Document No. textbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:49:32]]></Time>
<TimeTick>1574264972</TimeTick>
<NodeArgs eType="General" icon="0" nRep="68" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[6: Type 5105600147 in Invoice Document No. textbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:49:35]]></Time>
<TimeTick>1574264975</TimeTick>
<NodeArgs eType="General" icon="0" nRep="69" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[8: Click on Invoicing Party / AN...  was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:49:36]]></Time>
<TimeTick>1574264976</TimeTick>
<NodeArgs eType="General" icon="0" nRep="70" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[10: Click on Go  was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:49:36]]></Time>
<TimeTick>1574264976</TimeTick>
<NodeArgs eType="General" icon="0" nRep="71" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11/20/2019 - 18:49:00" eTime="11/20/2019 - 18:49:39" passed="9" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="62" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="61" status="Passed" >
<Disp><![CDATA[1.4.2 Iteration 4 (Row 4)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="11/20/2019 - 18:45:14" eTime="11/20/2019 - 18:49:40" passed="51" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="4" status="Passed" >
<Disp><![CDATA[Test 1.4.2 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>