<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Belarus Standard Time">
<General productName="Vugen" productVer="12" os="" host="LXIBY793"><DocLocation><![CDATA[D:\dev\Vuser_Scripts\1.1.TC]]></DocLocation></General>
<Doc rID="T1"   productName= "Vugen"  >
<DName><![CDATA[1.1.TC]]></DName>
<Res><![CDATA[result1]]></Res>
<Action rID="T2">
<AName><![CDATA[Init]]></AName>
<Summary sTime="11/22/2019 - 13:14:09" eTime="11/22/2019 - 13:14:09" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="5" >
<Disp><![CDATA[Init Summary]]></Disp>
</NodeArgs>
</Action>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Navigate to https://procurepartestc1.../site#Shell-home was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:14:12]]></Time>
<TimeTick>1574417652</TimeTick>
<NodeArgs eType="General" icon="0" nRep="9" status="Passed" >
<Disp><![CDATA[Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.2: Type yauhen.hedrevich@sap.com in Welcome to Procurement... textbox was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:14:21]]></Time>
<TimeTick>1574417661</TimeTick>
<NodeArgs eType="General" icon="0" nRep="10" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.4: Type ************** in Password passwordbox was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:14:27]]></Time>
<TimeTick>1574417667</TimeTick>
<NodeArgs eType="General" icon="0" nRep="11" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2.5: Click on Log On button was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:14:31]]></Time>
<TimeTick>1574417671</TimeTick>
<NodeArgs eType="General" icon="0" nRep="12" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3: Click on link (1) link was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:14:36]]></Time>
<TimeTick>1574417676</TimeTick>
<NodeArgs eType="General" icon="0" nRep="13" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[5: Click on Search searchbox was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:14:41]]></Time>
<TimeTick>1574417681</TimeTick>
<NodeArgs eType="General" icon="0" nRep="14" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[6: Type 0000100371 in Search searchbox was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:14:45]]></Time>
<TimeTick>1574417685</TimeTick>
<NodeArgs eType="General" icon="0" nRep="15" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[8: Click on Search  was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:14:46]]></Time>
<TimeTick>1574417686</TimeTick>
<NodeArgs eType="General" icon="0" nRep="16" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until Mar 16, 2019  exists was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:14:51]]></Time>
<TimeTick>1574417691</TimeTick>
<NodeArgs eType="General" icon="0" nRep="17" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[12: Click on Invoice Number / 2019  was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:14:51]]></Time>
<TimeTick>1574417691</TimeTick>
<NodeArgs eType="General" icon="0" nRep="18" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11/22/2019 - 13:14:10" eTime="11/22/2019 - 13:14:51" passed="10" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="8" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="7" status="Passed" >
<Disp><![CDATA[1.1.TC Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T15" iterID="2" >
<Action rID="T16">
<AName><![CDATA[Action]]></AName>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Navigate to https://procurepartestc1.../site#Shell-home was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:14:53]]></Time>
<TimeTick>1574417693</TimeTick>
<NodeArgs eType="General" icon="0" nRep="23" status="Passed" >
<Disp><![CDATA[Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.2: Type yauhen.hedrevich@sap.com in Welcome to Procurement... textbox was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:15:02]]></Time>
<TimeTick>1574417702</TimeTick>
<NodeArgs eType="General" icon="0" nRep="24" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.4: Type ************** in Password passwordbox was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:15:07]]></Time>
<TimeTick>1574417707</TimeTick>
<NodeArgs eType="General" icon="0" nRep="25" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2.5: Click on Log On button was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:15:11]]></Time>
<TimeTick>1574417711</TimeTick>
<NodeArgs eType="General" icon="0" nRep="26" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3: Click on link (1) link was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:15:17]]></Time>
<TimeTick>1574417717</TimeTick>
<NodeArgs eType="General" icon="0" nRep="27" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[5: Click on Search searchbox was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:15:20]]></Time>
<TimeTick>1574417720</TimeTick>
<NodeArgs eType="General" icon="0" nRep="28" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[6: Type 0000100371 in Search searchbox was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:15:26]]></Time>
<TimeTick>1574417726</TimeTick>
<NodeArgs eType="General" icon="0" nRep="29" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[8: Click on Search  was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:15:27]]></Time>
<TimeTick>1574417727</TimeTick>
<NodeArgs eType="General" icon="0" nRep="30" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until Mar 16, 2019  exists was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:15:32]]></Time>
<TimeTick>1574417732</TimeTick>
<NodeArgs eType="General" icon="0" nRep="31" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[12: Click on Invoice Number / 2019  was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:15:32]]></Time>
<TimeTick>1574417732</TimeTick>
<NodeArgs eType="General" icon="0" nRep="32" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11/22/2019 - 13:14:52" eTime="11/22/2019 - 13:15:32" passed="10" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="22" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="21" status="Passed" >
<Disp><![CDATA[1.1.TC Iteration 2 (Row 2)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T27" iterID="3" >
<Action rID="T28">
<AName><![CDATA[Action]]></AName>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Navigate to https://procurepartestc1.../site#Shell-home was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:15:35]]></Time>
<TimeTick>1574417735</TimeTick>
<NodeArgs eType="General" icon="0" nRep="37" status="Passed" >
<Disp><![CDATA[Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.2: Type yauhen.hedrevich@sap.com in Welcome to Procurement... textbox was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:15:44]]></Time>
<TimeTick>1574417744</TimeTick>
<NodeArgs eType="General" icon="0" nRep="38" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.4: Type ************** in Password passwordbox was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:15:49]]></Time>
<TimeTick>1574417749</TimeTick>
<NodeArgs eType="General" icon="0" nRep="39" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2.5: Click on Log On button was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:15:53]]></Time>
<TimeTick>1574417753</TimeTick>
<NodeArgs eType="General" icon="0" nRep="40" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3: Click on link (1) link was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:15:58]]></Time>
<TimeTick>1574417758</TimeTick>
<NodeArgs eType="General" icon="0" nRep="41" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[5: Click on Search searchbox was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:16:03]]></Time>
<TimeTick>1574417763</TimeTick>
<NodeArgs eType="General" icon="0" nRep="42" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[6: Type 0000100371 in Search searchbox was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:16:08]]></Time>
<TimeTick>1574417768</TimeTick>
<NodeArgs eType="General" icon="0" nRep="43" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[8: Click on Search  was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:16:09]]></Time>
<TimeTick>1574417769</TimeTick>
<NodeArgs eType="General" icon="0" nRep="44" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until Mar 16, 2019  exists was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:16:13]]></Time>
<TimeTick>1574417773</TimeTick>
<NodeArgs eType="General" icon="0" nRep="45" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[12: Click on Invoice Number / 2019  was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:16:14]]></Time>
<TimeTick>1574417774</TimeTick>
<NodeArgs eType="General" icon="0" nRep="46" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11/22/2019 - 13:15:33" eTime="11/22/2019 - 13:16:14" passed="10" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="36" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="35" status="Passed" >
<Disp><![CDATA[1.1.TC Iteration 3 (Row 3)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T39" iterID="4" >
<Action rID="T40">
<AName><![CDATA[Action]]></AName>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Navigate to https://procurepartestc1.../site#Shell-home was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:16:16]]></Time>
<TimeTick>1574417776</TimeTick>
<NodeArgs eType="General" icon="0" nRep="51" status="Passed" >
<Disp><![CDATA[Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.2: Type yauhen.hedrevich@sap.com in Welcome to Procurement... textbox was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:16:25]]></Time>
<TimeTick>1574417785</TimeTick>
<NodeArgs eType="General" icon="0" nRep="52" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.4: Type ************** in Password passwordbox was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:16:31]]></Time>
<TimeTick>1574417791</TimeTick>
<NodeArgs eType="General" icon="0" nRep="53" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2.5: Click on Log On button was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:16:37]]></Time>
<TimeTick>1574417797</TimeTick>
<NodeArgs eType="General" icon="0" nRep="54" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3: Click on link (1) link was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:16:46]]></Time>
<TimeTick>1574417806</TimeTick>
<NodeArgs eType="General" icon="0" nRep="55" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[5: Click on Search searchbox was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:16:47]]></Time>
<TimeTick>1574417807</TimeTick>
<NodeArgs eType="General" icon="0" nRep="56" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[6: Type 0000100371 in Search searchbox was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:16:51]]></Time>
<TimeTick>1574417811</TimeTick>
<NodeArgs eType="General" icon="0" nRep="57" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[8: Click on Search  was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:16:52]]></Time>
<TimeTick>1574417812</TimeTick>
<NodeArgs eType="General" icon="0" nRep="58" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until Mar 16, 2019  exists was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:16:57]]></Time>
<TimeTick>1574417817</TimeTick>
<NodeArgs eType="General" icon="0" nRep="59" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[12: Click on Invoice Number / 2019  was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:16:57]]></Time>
<TimeTick>1574417817</TimeTick>
<NodeArgs eType="General" icon="0" nRep="60" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11/22/2019 - 13:16:14" eTime="11/22/2019 - 13:16:57" passed="10" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="50" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="49" status="Passed" >
<Disp><![CDATA[1.1.TC Iteration 4 (Row 4)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T51" iterID="5" >
<Action rID="T52">
<AName><![CDATA[Action]]></AName>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Navigate to https://procurepartestc1.../site#Shell-home was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:16:59]]></Time>
<TimeTick>1574417819</TimeTick>
<NodeArgs eType="General" icon="0" nRep="65" status="Passed" >
<Disp><![CDATA[Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.2: Type yauhen.hedrevich@sap.com in Welcome to Procurement... textbox was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:17:09]]></Time>
<TimeTick>1574417829</TimeTick>
<NodeArgs eType="General" icon="0" nRep="66" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.4: Type ************** in Password passwordbox was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:17:16]]></Time>
<TimeTick>1574417836</TimeTick>
<NodeArgs eType="General" icon="0" nRep="67" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2.5: Click on Log On button was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:17:18]]></Time>
<TimeTick>1574417838</TimeTick>
<NodeArgs eType="General" icon="0" nRep="68" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3: Click on link (1) link was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:17:38]]></Time>
<TimeTick>1574417858</TimeTick>
<NodeArgs eType="General" icon="0" nRep="69" status="Failed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11/22/2019 - 13:16:57" eTime="11/22/2019 - 13:17:39" passed="4" failed="1" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="64" status="Failed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="63" status="Failed" >
<Disp><![CDATA[1.1.TC Iteration 5 (Row 5)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T58" iterID="6" >
<Action rID="T59">
<AName><![CDATA[Action]]></AName>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Navigate to https://procurepartestc1.../site#Shell-home was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:17:41]]></Time>
<TimeTick>1574417861</TimeTick>
<NodeArgs eType="General" icon="0" nRep="74" status="Passed" >
<Disp><![CDATA[Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.2: Type yauhen.hedrevich@sap.com in Welcome to Procurement... textbox was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:17:50]]></Time>
<TimeTick>1574417870</TimeTick>
<NodeArgs eType="General" icon="0" nRep="75" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.4: Type ************** in Password passwordbox was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:17:56]]></Time>
<TimeTick>1574417876</TimeTick>
<NodeArgs eType="General" icon="0" nRep="76" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2.5: Click on Log On button was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:18:02]]></Time>
<TimeTick>1574417882</TimeTick>
<NodeArgs eType="General" icon="0" nRep="77" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3: Click on link (1) link was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:18:10]]></Time>
<TimeTick>1574417890</TimeTick>
<NodeArgs eType="General" icon="0" nRep="78" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[5: Click on Search searchbox was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:18:11]]></Time>
<TimeTick>1574417891</TimeTick>
<NodeArgs eType="General" icon="0" nRep="79" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[6: Type 0000100371 in Search searchbox was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:18:16]]></Time>
<TimeTick>1574417896</TimeTick>
<NodeArgs eType="General" icon="0" nRep="80" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[8: Click on Search  was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:18:17]]></Time>
<TimeTick>1574417897</TimeTick>
<NodeArgs eType="General" icon="0" nRep="81" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until Mar 16, 2019  exists was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:18:22]]></Time>
<TimeTick>1574417902</TimeTick>
<NodeArgs eType="General" icon="0" nRep="82" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[12: Click on Invoice Number / 2019  was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:18:22]]></Time>
<TimeTick>1574417902</TimeTick>
<NodeArgs eType="General" icon="0" nRep="83" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11/22/2019 - 13:17:39" eTime="11/22/2019 - 13:18:22" passed="10" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="73" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="72" status="Passed" >
<Disp><![CDATA[1.1.TC Iteration 6 (Row 6)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T70" iterID="7" >
<Action rID="T71">
<AName><![CDATA[Action]]></AName>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Navigate to https://procurepartestc1.../site#Shell-home was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:18:25]]></Time>
<TimeTick>1574417905</TimeTick>
<NodeArgs eType="General" icon="0" nRep="88" status="Passed" >
<Disp><![CDATA[Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.2: Type yauhen.hedrevich@sap.com in Welcome to Procurement... textbox was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:18:34]]></Time>
<TimeTick>1574417914</TimeTick>
<NodeArgs eType="General" icon="0" nRep="89" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.4: Type ************** in Password passwordbox was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:18:40]]></Time>
<TimeTick>1574417920</TimeTick>
<NodeArgs eType="General" icon="0" nRep="90" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T75">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2.5: Click on Log On button was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:18:44]]></Time>
<TimeTick>1574417924</TimeTick>
<NodeArgs eType="General" icon="0" nRep="91" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T76">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3: Click on link (1) link was finished]]></Details>
<Time><![CDATA[11/22/2019 - 13:18:49]]></Time>
<TimeTick>1574417929</TimeTick>
<NodeArgs eType="General" icon="0" nRep="92" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T77">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>