<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Belarus Standard Time">
<General productName="Vugen" productVer="12" os="" host="LXIBY793"><DocLocation><![CDATA[D:\dev\Vuser_Scripts\1.4]]></DocLocation></General>
<Doc rID="T1"   productName= "Vugen"  >
<DName><![CDATA[1.4]]></DName>
<Res><![CDATA[result1]]></Res>
<Action rID="T2">
<AName><![CDATA[Init]]></AName>
<Summary sTime="11/20/2019 - 18:05:35" eTime="11/20/2019 - 18:05:35" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="5" >
<Disp><![CDATA[Init Summary]]></Disp>
</NodeArgs>
</Action>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Navigate to https://procurepartestc1.../site#Shell-home was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:05:38]]></Time>
<TimeTick>1574262338</TimeTick>
<NodeArgs eType="General" icon="0" nRep="9" status="Passed" >
<Disp><![CDATA[Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.1: Type yauhen.hedrevich@sap.com in Welcome to Procurement... textbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:05:48]]></Time>
<TimeTick>1574262348</TimeTick>
<NodeArgs eType="General" icon="0" nRep="10" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.3: Type ************** in Password passwordbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:05:54]]></Time>
<TimeTick>1574262354</TimeTick>
<NodeArgs eType="General" icon="0" nRep="11" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Press Key]]></Obj>
<Details plainTxt="False" ><![CDATA[2.4: Press key Enter on Password passwordbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:06:02]]></Time>
<TimeTick>1574262362</TimeTick>
<NodeArgs eType="General" icon="0" nRep="12" status="Passed" >
<Disp><![CDATA[Press Key]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3: Click on link (1) link was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:06:08]]></Time>
<TimeTick>1574262368</TimeTick>
<NodeArgs eType="General" icon="0" nRep="13" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[5: Click on Invoice Document No. textbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:06:09]]></Time>
<TimeTick>1574262369</TimeTick>
<NodeArgs eType="General" icon="0" nRep="14" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[6: Type 5105600147 in Invoice Document No. textbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:06:14]]></Time>
<TimeTick>1574262374</TimeTick>
<NodeArgs eType="General" icon="0" nRep="15" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[8: Click on Company Code in Connected... gridcell was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:06:15]]></Time>
<TimeTick>1574262375</TimeTick>
<NodeArgs eType="General" icon="0" nRep="16" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[9: Click on Go  was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:06:16]]></Time>
<TimeTick>1574262376</TimeTick>
<NodeArgs eType="General" icon="0" nRep="17" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[11: Click on Invoicing Party / AN... gridcell was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:06:20]]></Time>
<TimeTick>1574262380</TimeTick>
<NodeArgs eType="General" icon="0" nRep="18" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[13: Click on More button was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:06:20]]></Time>
<TimeTick>1574262380</TimeTick>
<NodeArgs eType="General" icon="0" nRep="19" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[15: Click on Attachments option was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:06:21]]></Time>
<TimeTick>1574262381</TimeTick>
<NodeArgs eType="General" icon="0" nRep="20" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until Plugin  exists was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:06:24]]></Time>
<TimeTick>1574262384</TimeTick>
<NodeArgs eType="General" icon="0" nRep="21" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[17: Click on Last Updated on Apr 11,...  was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:06:24]]></Time>
<TimeTick>1574262384</TimeTick>
<NodeArgs eType="General" icon="0" nRep="22" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11/20/2019 - 18:05:36" eTime="11/20/2019 - 18:06:24" passed="14" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="8" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="7" status="Passed" >
<Disp><![CDATA[1.4 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T19" iterID="2" >
<Action rID="T20">
<AName><![CDATA[Action]]></AName>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Navigate to https://procurepartestc1.../site#Shell-home was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:06:37]]></Time>
<TimeTick>1574262397</TimeTick>
<NodeArgs eType="General" icon="0" nRep="27" status="Passed" >
<Disp><![CDATA[Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.1: Type yauhen.hedrevich@sap.com in Welcome to Procurement... textbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:06:47]]></Time>
<TimeTick>1574262407</TimeTick>
<NodeArgs eType="General" icon="0" nRep="28" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.3: Type ************** in Password passwordbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:06:53]]></Time>
<TimeTick>1574262413</TimeTick>
<NodeArgs eType="General" icon="0" nRep="29" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Press Key]]></Obj>
<Details plainTxt="False" ><![CDATA[2.4: Press key Enter on Password passwordbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:07:02]]></Time>
<TimeTick>1574262422</TimeTick>
<NodeArgs eType="General" icon="0" nRep="30" status="Passed" >
<Disp><![CDATA[Press Key]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3: Click on link (1) link was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:07:08]]></Time>
<TimeTick>1574262428</TimeTick>
<NodeArgs eType="General" icon="0" nRep="31" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[5: Click on Invoice Document No. textbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:07:10]]></Time>
<TimeTick>1574262430</TimeTick>
<NodeArgs eType="General" icon="0" nRep="32" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[6: Type 5105600147 in Invoice Document No. textbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:07:14]]></Time>
<TimeTick>1574262434</TimeTick>
<NodeArgs eType="General" icon="0" nRep="33" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[8: Click on Company Code in Connected... gridcell was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:07:15]]></Time>
<TimeTick>1574262435</TimeTick>
<NodeArgs eType="General" icon="0" nRep="34" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[9: Click on Go  was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:07:16]]></Time>
<TimeTick>1574262436</TimeTick>
<NodeArgs eType="General" icon="0" nRep="35" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[11: Click on Invoicing Party / AN... gridcell was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:07:21]]></Time>
<TimeTick>1574262441</TimeTick>
<NodeArgs eType="General" icon="0" nRep="36" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[13: Click on More button was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:07:22]]></Time>
<TimeTick>1574262442</TimeTick>
<NodeArgs eType="General" icon="0" nRep="37" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[15: Click on Attachments option was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:07:22]]></Time>
<TimeTick>1574262442</TimeTick>
<NodeArgs eType="General" icon="0" nRep="38" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until Plugin  exists was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:07:25]]></Time>
<TimeTick>1574262445</TimeTick>
<NodeArgs eType="General" icon="0" nRep="39" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[17: Click on Last Updated on Apr 11,...  was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:07:25]]></Time>
<TimeTick>1574262445</TimeTick>
<NodeArgs eType="General" icon="0" nRep="40" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11/20/2019 - 18:06:36" eTime="11/20/2019 - 18:07:25" passed="14" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="26" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="25" status="Passed" >
<Disp><![CDATA[1.4 Iteration 2 (Row 2)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T35" iterID="3" >
<Action rID="T36">
<AName><![CDATA[Action]]></AName>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Navigate to https://procurepartestc1.../site#Shell-home was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:07:37]]></Time>
<TimeTick>1574262457</TimeTick>
<NodeArgs eType="General" icon="0" nRep="45" status="Passed" >
<Disp><![CDATA[Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.1: Type yauhen.hedrevich@sap.com in Welcome to Procurement... textbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:07:47]]></Time>
<TimeTick>1574262467</TimeTick>
<NodeArgs eType="General" icon="0" nRep="46" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.3: Type ************** in Password passwordbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:07:53]]></Time>
<TimeTick>1574262473</TimeTick>
<NodeArgs eType="General" icon="0" nRep="47" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Press Key]]></Obj>
<Details plainTxt="False" ><![CDATA[2.4: Press key Enter on Password passwordbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:08:01]]></Time>
<TimeTick>1574262481</TimeTick>
<NodeArgs eType="General" icon="0" nRep="48" status="Passed" >
<Disp><![CDATA[Press Key]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3: Click on link (1) link was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:08:08]]></Time>
<TimeTick>1574262488</TimeTick>
<NodeArgs eType="General" icon="0" nRep="49" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[5: Click on Invoice Document No. textbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:08:09]]></Time>
<TimeTick>1574262489</TimeTick>
<NodeArgs eType="General" icon="0" nRep="50" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[6: Type 5105600147 in Invoice Document No. textbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:08:13]]></Time>
<TimeTick>1574262493</TimeTick>
<NodeArgs eType="General" icon="0" nRep="51" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[8: Click on Company Code in Connected... gridcell was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:08:14]]></Time>
<TimeTick>1574262494</TimeTick>
<NodeArgs eType="General" icon="0" nRep="52" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[9: Click on Go  was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:08:15]]></Time>
<TimeTick>1574262495</TimeTick>
<NodeArgs eType="General" icon="0" nRep="53" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[11: Click on Invoicing Party / AN... gridcell was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:08:19]]></Time>
<TimeTick>1574262499</TimeTick>
<NodeArgs eType="General" icon="0" nRep="54" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[13: Click on More button was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:08:20]]></Time>
<TimeTick>1574262500</TimeTick>
<NodeArgs eType="General" icon="0" nRep="55" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[15: Click on Attachments option was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:08:20]]></Time>
<TimeTick>1574262500</TimeTick>
<NodeArgs eType="General" icon="0" nRep="56" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until Plugin  exists was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:08:23]]></Time>
<TimeTick>1574262503</TimeTick>
<NodeArgs eType="General" icon="0" nRep="57" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[17: Click on Last Updated on Apr 11,...  was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:08:23]]></Time>
<TimeTick>1574262503</TimeTick>
<NodeArgs eType="General" icon="0" nRep="58" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11/20/2019 - 18:07:36" eTime="11/20/2019 - 18:08:23" passed="14" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="44" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="43" status="Passed" >
<Disp><![CDATA[1.4 Iteration 3 (Row 3)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T51" iterID="4" >
<Action rID="T52">
<AName><![CDATA[Action]]></AName>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Navigate to https://procurepartestc1.../site#Shell-home was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:08:37]]></Time>
<TimeTick>1574262517</TimeTick>
<NodeArgs eType="General" icon="0" nRep="63" status="Passed" >
<Disp><![CDATA[Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.1: Type yauhen.hedrevich@sap.com in Welcome to Procurement... textbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:08:45]]></Time>
<TimeTick>1574262525</TimeTick>
<NodeArgs eType="General" icon="0" nRep="64" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.3: Type ************** in Password passwordbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:08:51]]></Time>
<TimeTick>1574262531</TimeTick>
<NodeArgs eType="General" icon="0" nRep="65" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Press Key]]></Obj>
<Details plainTxt="False" ><![CDATA[2.4: Press key Enter on Password passwordbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:08:59]]></Time>
<TimeTick>1574262539</TimeTick>
<NodeArgs eType="General" icon="0" nRep="66" status="Passed" >
<Disp><![CDATA[Press Key]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3: Click on link (1) link was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:09:00]]></Time>
<TimeTick>1574262540</TimeTick>
<NodeArgs eType="General" icon="0" nRep="67" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[5: Click on Invoice Document No. textbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:09:07]]></Time>
<TimeTick>1574262547</TimeTick>
<NodeArgs eType="General" icon="0" nRep="68" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[6: Type 5105600147 in Invoice Document No. textbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:09:10]]></Time>
<TimeTick>1574262550</TimeTick>
<NodeArgs eType="General" icon="0" nRep="69" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[8: Click on Company Code in Connected... gridcell was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:09:11]]></Time>
<TimeTick>1574262551</TimeTick>
<NodeArgs eType="General" icon="0" nRep="70" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[9: Click on Go  was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:09:12]]></Time>
<TimeTick>1574262552</TimeTick>
<NodeArgs eType="General" icon="0" nRep="71" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[11: Click on Invoicing Party / AN... gridcell was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:09:16]]></Time>
<TimeTick>1574262556</TimeTick>
<NodeArgs eType="General" icon="0" nRep="72" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[13: Click on More button was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:09:16]]></Time>
<TimeTick>1574262556</TimeTick>
<NodeArgs eType="General" icon="0" nRep="73" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[15: Click on Attachments option was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:09:17]]></Time>
<TimeTick>1574262557</TimeTick>
<NodeArgs eType="General" icon="0" nRep="74" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until Plugin  exists was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:09:20]]></Time>
<TimeTick>1574262560</TimeTick>
<NodeArgs eType="General" icon="0" nRep="75" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[17: Click on Last Updated on Apr 11,...  was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:09:20]]></Time>
<TimeTick>1574262560</TimeTick>
<NodeArgs eType="General" icon="0" nRep="76" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11/20/2019 - 18:08:36" eTime="11/20/2019 - 18:09:20" passed="14" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="62" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="61" status="Passed" >
<Disp><![CDATA[1.4 Iteration 4 (Row 4)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T67" iterID="5" >
<Action rID="T68">
<AName><![CDATA[Action]]></AName>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Navigate to https://procurepartestc1.../site#Shell-home was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:09:38]]></Time>
<TimeTick>1574262578</TimeTick>
<NodeArgs eType="General" icon="0" nRep="81" status="Passed" >
<Disp><![CDATA[Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.1: Type yauhen.hedrevich@sap.com in Welcome to Procurement... textbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:09:47]]></Time>
<TimeTick>1574262587</TimeTick>
<NodeArgs eType="General" icon="0" nRep="82" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.3: Type ************** in Password passwordbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:09:53]]></Time>
<TimeTick>1574262593</TimeTick>
<NodeArgs eType="General" icon="0" nRep="83" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[Press Key]]></Obj>
<Details plainTxt="False" ><![CDATA[2.4: Press key Enter on Password passwordbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:10:07]]></Time>
<TimeTick>1574262607</TimeTick>
<NodeArgs eType="General" icon="0" nRep="84" status="Passed" >
<Disp><![CDATA[Press Key]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3: Click on link (1) link was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:10:08]]></Time>
<TimeTick>1574262608</TimeTick>
<NodeArgs eType="General" icon="0" nRep="85" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[5: Click on Invoice Document No. textbox was finished]]></Details>
<Time><![CDATA[11/20/2019 - 18:10:21]]></Time>
<TimeTick>1574262621</TimeTick>
<NodeArgs eType="General" icon="0" nRep="86" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T75">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>